      PROGRAM MAIN

      INTEGER Z_PARAM
      INTEGER N_PARAM
      INTEGER M_PARAM

      PARAMETER(N_PARAM = 263743)
      PARAMETER(M_PARAM = 263743)
      PARAMETER (Z_PARAM=1302464)

      INTEGER IUNIT,OUNIT
      CHARACTER REP*10
      CHARACTER FIELD*7
      CHARACTER SYMM*19
      CHARACTER IFILE*32,OFILE*32
      INTEGER IVAL(Z_PARAM)
      DOUBLE PRECISION RVAL(Z_PARAM)
      COMPLEX CVAL(Z_PARAM)


      INTEGER INDROW(Z_PARAM)
      INTEGER INDCOL(Z_PARAM)
      INTEGER IPNTR(N_PARAM+1)
      INTEGER JPNTR(N_PARAM+1)
      INTEGER IWA(6*N_PARAM+1)
      INTEGER MAXCLQ
      
      INTEGER I,J,K,JP,IR

C
      IF (IARGC() .GT. 0) THEN
         CALL GETARG(1,IFILE)
         IUNIT = 8
         OPEN(UNIT=IUNIT,FILE=IFILE)
      ELSE
         IUNIT = 5
      ENDIF
      PRINT *,'READING HEADER ONLY...'
      CALL MMINFO(IUNIT,REP,FIELD,SYMM,NROWS,NCOLS,NNZ)
      PRINT *,'  MATRIX IS TYPE: ',REP,' ',FIELD,' ',SYMM
      PRINT *,'  MATRIX SIZE: ',NROWS,' BY ',NCOLS,' WITH ',
     *                          NNZ,' NONZEROS.'
C
      PRINT *,'READING HEADER AND DATA...'
      CALL MMREAD(IUNIT,REP,FIELD,SYMM,NROWS,NCOLS,NNZ,Z_PARAM,
     *           INDROW,INDCOL,IVAL,RVAL,CVAL)
      PRINT *,'  MATRIX IS TYPE: ',REP,' ',FIELD,' ',SYMM
      PRINT *,'  MATRIX SIZE: ',NROWS,' BY ',NCOLS,' WITH ',
     *                          NNZ,' NONZEROS.'
      CALL SRTDAT(NCOLS,NNZ,INDROW,INDCOL,JPNTR,IWA)

      DO 20 I = 1, NROWS
         IWA(I) = 0
   20    CONTINUE
      NNZ = 1
      DO 45 J = 1, NCOLS
         K = NNZ
         DO 30 JP = JPNTR(J), JPNTR(J+1)-1
            IR = INDROW(JP)
            IF (IWA(IR) .NE. J) THEN
               INDROW(NNZ) = IR
               NNZ = NNZ + 1
               IWA(IR) = J
               END IF
   30       CONTINUE
         JPNTR(J) = K
 45      CONTINUE
      JPNTR(NCOLS+1) = NNZ


      CALL SETR(NROWS,NCOLS,INDROW,JPNTR,INDCOL,IPNTR,IWA)

      CALL DEGR(NCOLS,INDROW,JPNTR,INDCOL,IPNTR,IWA(5*NCOLS+1)
     *     ,IWA(NCOLS+1))

      DO 40 I = 1,NNZ
         PRINT *,INDROW(I),',',INDCOL(I)
 40   CONTINUE
      
      DO 50 I = 1,NCOLS+1
         PRINT *,JPNTR(I),',',IPNTR(I),',',IWA(5*NCOLS+1+I)
c         PRINT *,JPNTR(I),',',IPNTR(I)
 50   CONTINUE

      STOP
      END

